### PR TITLE
Bring role from fedcloud-catchall-ops repo

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Initial commit, bringing content

---

**Related issue :**

### CODE REVIEW

**Comment by gwarf** [comment]
I think it would be great to check how this follows/could follow https://github.com/EGI-Foundation/ansible-style-guide

**Comment by enolfc** [comment]
i

> I think it would be great to check how this follows/could follow https://github.com/EGI-Foundation/ansible-style-guide

it does miss testing and publishing to ansible-galaxy. Otherwise I think it complains with it

**Comment by gwarf** [comment]
> > I think it would be great to check how this follows/could follow https://github.com/EGI-Foundation/ansible-style-guide
> 
> it does miss testing and publishing to ansible-galaxy. Otherwise I think it complains with it

So I was quite a lot thinking about the molecule-based testing: https://docs.egi.eu/ansible-style-guide/test

**Comment by enolfc** [comment]
used admin powers to merge this one. It now also includes testing with molecule

**Pull request merged**
